layouts/default.vue
Fixes https://github.com/jsdelivr/globalping-dash/issues/16
=> fix: scroll only content on desktop

components/CreditsChart.vue, layouts/default.vue
Related to https://github.com/jsdelivr/globalping-dash/issues/17
Not able to reproduce the original issue, but this fixes the thing that might be the root problem.
=> fix: horizontal scroll on credits page

components/AdoptProbe.vue, composables/pagination.ts, pages/credits.vue, pages/probes.vue, pages/probes/[id].vue, pages/settings.vue, pages/tokens.vue, presets/aura/toast/index.js
Fixes https://github.com/jsdelivr/globalping-dash/issues/15
=> feat: update url during pagination

assets/css/base.css, pages/probes/[id].vue, plugins/02.refreshToken.ts, plugins/04.theme.ts, store/appearance.ts, store/auth.ts, utils/dark-map-styles.json, utils/init-google-map.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/22
Fixes https://github.com/jsdelivr/globalping-dash/issues/23
=> feat: persist dark theme in localstorage

components/ReadOnlyAutoComplete.vue, nuxt.config.ts, package.json, pages/probes.vue, pages/probes/[id].vue, pages/settings.vue, pnpm-lock.yaml, presets/aura/autocomplete/index.js, types.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/25
=> feat: show all probe tags

components/CreditsChart.vue, pages/credits.vue, pages/probes.vue, types.ts
Even in cases when there are more than 100 entries in the past month.
=> fix: show correct values for credits totals

components/AdoptProbe.vue, components/TokenDetails.vue, nuxt.config.ts, pages/credits.vue, pages/index.vue, pages/probes.vue, pages/tokens.vue, types.ts
Part of https://github.com/jsdelivr/globalping-dash-directus/issues/27
=> feat: add e2e test ids

pages/credits.vue, pages/probes.vue
Part of https://github.com/jsdelivr/globalping-dash-directus/issues/42
=> feat: receive sum as number

components/AddCredits.vue, components/GPDialog.vue, nuxt.config.ts, pages/credits.vue, pages/index.vue, pages/login.vue, presets/aura/button/index.js, store/auth.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/34
=> feat: credits steps modal

components/ApplicationOptions.vue, components/TokenDetails.vue, composables/pagination.ts, pages/probes/[id].vue, pages/tokens.vue, store/auth.ts, types.ts, utils/date-formatters.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/14
=> feat: applications table

README.md
Fixes https://github.com/jsdelivr/globalping-dash/issues/53
=> feat: add contribution guide

components/AddCredits.vue, layouts/default.vue, nuxt.config.ts, pages/credits.vue, pages/index.vue, pages/probes.vue, pages/probes/[id].vue, pages/settings.vue, plugins/05.setMetadata.ts, presets/aura/checkbox/index.js, presets/aura/index.js, presets/aura/toggleswitch/index.js, store/auth.ts, store/metadata.ts, types.ts, utils/probe-status.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/51
=> feat: old HW firmware/node notification

components/AddCredits.vue, pages/credits.vue, pages/index.vue, pages/probes.vue, pages/probes/[id].vue, types.ts
Part of https://github.com/jsdelivr/globalping-dash-directus/issues/58
=> feat: use gp_probes instead of gp_adopted_probes

pages/settings.vue, store/auth.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/71
=> fix: logout 500 error

components/AddCredits.vue, components/AdoptProbe.vue, components/ProbeAdoptedContent.vue, components/StartProbeCommands.vue, layouts/default.vue, pages/authorize/[publicCodeId].vue, pages/credits.vue, pages/index.vue, pages/notifications.vue, pages/probes.vue, pages/probes/[id].vue, pages/settings.vue, pages/tokens.vue, store/auth.ts, types.ts
Fixes https://github.com/jsdelivr/globalping-dash/issues/69
=> feat: add default tag prefix setting

components/ProbeAdoptedContent.vue, composables/useInboxNotificationIds.ts, composables/useNotifications.ts, layouts/default.vue, pages/notifications.vue
Fixes https://github.com/jsdelivr/globalping-dash/issues/68
=> feat: refresh notifications at the end of adoption flow

pages/credits.vue
Part of https://github.com/jsdelivr/globalping-dash/issues/86
=> feat: simplify credits pagination

components/AdoptProbe.vue, components/CreditsChart.vue, components/ProbeAdoptedContent.vue, composables/useUserFilter.ts, pages/credits.vue, pages/index.vue, pages/probes/index.vue, pages/settings.vue, pages/tokens.vue, store/auth.ts, types.ts, utils/date-formatters.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/91
=> feat: impersonation on custom endpoints

pages/probes/[id].vue, utils/probe-status.ts
=> feat: add warning message for outdated firmware and container versions

components/AdminPanel.vue
=> fix: only clear impersonation when switching admin mode on

presets/aura/inputotp/index.js
Closes #109 
Change needed due to https://github.com/primefaces/primevue/commit/5bc8f2a8e36354168bd0c14b5bda3462f4a7d04b
=> fix: update input otp data selector

pages/probes/index.vue
@PavelKopecky test after https://github.com/jsdelivr/globalping-dash-directus/issues/121
=> fix: use text-ellipsis for long network names

components/CityAutoComplete.vue, components/probe/LocationInput.vue, types.ts
=> feat: allow storing empty city value

composables/computedDebounced.ts, pages/probes/index.vue
=> fix: double fetch on probe list page

app/components/AddCredits.vue, app/pages/index.vue, app/types.ts
Addresses the first 2 points of #114
=> feat: add sponsorship information

app/components/ShowMore.vue, app/components/StatusIcon.vue, app/pages/probes/[id].vue, app/utils/probe-status.ts
=> fix: alt ip container overflow

app/components/AsyncCell.vue, app/components/AsyncRow.vue, app/components/CodeBlock.vue, app/components/TokenDetails.vue, app/components/list-items/AppItem.vue, app/components/list-items/CreditItem.vue, app/components/list-items/TokenItem.vue, app/pages/credits.vue, app/pages/tokens.vue, app/presets/aura/autocomplete/index.js, app/utils/date-formatters.ts, app/utils/format-credit-comment.ts
=> feat: improve credits table on mobile devices
